### PR TITLE
Logging, anti-bruteforce, CRLs and tool recommendation

### PR DESCRIPTION
**Pull request by TheresNoPiLikeRaspberryPi**
Saw use in the following additions:

-A logging mechnism, so the owner of the phys. access control system is able to reconstruct who tried to enter when and wether access was granted.

-An anti-bruteforce-timelock mechanism. In the current state the authentication system loops as fast as possible to verifiy access authorization. An attacker could use this to try to get unauthorized access. 
(There are multiple ways known for the attacker to get access to the certificate, like sniffing, skimming, social engineering . So the attacker would need to try a lot of private keys). As a counter measure i thought of the following: If 3 times within 30 seconds an authentication-failure is recognized, the authentication will be locked for 30 seconds.

-Support of Certificate Revocation Lists (CRLs). Needed in case a smartcard is lost or stolen.

-For certificate management i´d recommend using XCA, as it is easier for less-technical users than using openssl via the shell. I´d locate this recommendation in the documentation. Would like to add a step by step guide for it also, because it could be valuable for less-technical users.

Looking forward to hear what you think about it.

### CODE REVIEW

**Comment by darconeous** [comment]
Ooo, wasn't expecting pull requests on this repo. I'll try to have a look at these changes over the weekend!

One comment though: Since the entropy in the private key is (usually) quite large (>80 bits), I'm not terribly worried about brute force attacks.

**Comment by darconeous** [comment]
I really like this commit, but I think the anti-bruteforce changes are unnecessary due to the entropy of the key sizes and the fact that you can't really expect an attacker to achieve a key test rate larger than 1 key/second. Otherwise I think this commit is great.

I'm inclined to accept it and remove the brute-force delay, but I wanted to get your feedback before doing that.

**Comment by TheresNoPiLikeRaspberryPi** [comment]
I´m glad you like it. Feel free to add the changes you feel 100% comfortable with.
I hope I´ll be able to elaborate my thoughts behind the anti-bruteforce part in the near future with the arguments that led me to think about it back then. Will need to search through some documents therefore ,but will report back subsequently.

**Comment by darconeous** [comment]
I'm curious about your application. I (obviously) put this code out there for people to use, but I guess I never really thought anyone would actually use it. :)

**Comment by interbiznw** [comment]
I also want to use it. Can you provide more information on the setup of the cards/access devices. I bought the same usb reader and would love to use the nfc in my phone and the nfc cards that came with it. 

Thanks, 
Jamie Owens 
Interbiznw.com

**Comment by TheresNoPiLikeRaspberryPi** [comment]
@darconeous 
currently i´m not able to setup the system on my doors, because i am not the owner. But i intend to make use of it as soon as i´m able to do so :)

@interbiznw 
I like that idea. 
Not sure if i get your question right, but I´ll try to answer:
Softwareside the PKCS#11 interface is used for communication. The openssl application is wrapping that for the developer. The project and thus the code are designed around the Personal Identity Verification that US government uses.
For succesful authentication the cards need to be initialized with a X.509 certificate and the corresponding private key. For cryptography, at least with the yubikey neo, RSA 2048 or ECC-prime-256 are used. Afterwards one needs to "register" that certficate in a whitelist on the Raspberry pi, in order to grant access rights to a person.

Does that answer your question? Just ask if there is still something unclear.

**Pull request merged**
